# Generated by Django 4.1.7 on 2023-03-25 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('author', models.CharField(max_length=22, verbose_name='Никнейм')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('describe', models.TextField(verbose_name='Содержание')),
                ('date', models.CharField(max_length=255, verbose_name='Дата окончания')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('author', models.CharField(max_length=22, verbose_name='Никнейм')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('number', models.IntegerField(default=1, verbose_name='Неделя')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('date', models.DateField(verbose_name='Дата')),
                ('first_is_active', models.BooleanField(default=False, verbose_name='Воздержание')),
                ('second_is_active', models.BooleanField(default=False, verbose_name='Порядок')),
                ('third_is_active', models.BooleanField(default=False, verbose_name='Бережливость')),
                ('fourth_is_active', models.BooleanField(default=False, verbose_name='Трудолюбие')),
                ('week', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.week', verbose_name='Неделя')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('author', models.CharField(max_length=22, verbose_name='Никнейм')),
                ('comment', models.TextField(verbose_name='Заголовок')),
                ('action', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.action', verbose_name='Действие')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='action',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card', verbose_name='карта'),
        ),
    ]
