# Generated by Django 4.1.7 on 2023-03-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_day_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='week',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
