# Generated by Django 4.1.7 on 2023-03-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_mainimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('author', models.CharField(max_length=22, verbose_name='Никнейм')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('describe', models.TextField(verbose_name='Содержание')),
                ('final_date', models.CharField(default='', max_length=255, verbose_name='Дата окончания')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
