# Generated by Django 4.1.7 on 2023-03-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_idea_actions_idea_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='actions',
            field=models.TextField(default='', verbose_name='Действия'),
        ),
    ]
