# Generated by Django 4.1.7 on 2023-03-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_idea_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='complexity',
            field=models.IntegerField(default=0, verbose_name='сложность'),
        ),
        migrations.AddField(
            model_name='action',
            name='importance',
            field=models.IntegerField(default=0, verbose_name='важность'),
        ),
    ]
