# Generated by Django 4.1.7 on 2023-03-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_action_complexity_action_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='complexity',
            field=models.IntegerField(default=0, verbose_name='сложность'),
        ),
        migrations.AddField(
            model_name='idea',
            name='importance',
            field=models.IntegerField(default=0, verbose_name='важность'),
        ),
    ]
