# Generated by Django 4.1.7 on 2023-03-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_idea_complexity_idea_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='participants',
            field=models.TextField(default='', verbose_name='Действия'),
        ),
    ]
