# Generated by Django 4.1.7 on 2023-04-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_idea_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='efficiency',
            field=models.IntegerField(default=0, verbose_name='Эффективность'),
        ),
    ]
