# Generated by Django 4.1.7 on 2023-04-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_card_efficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionToIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('author', models.CharField(max_length=22, verbose_name='Никнейм')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('describe', models.TextField(verbose_name='Содержание')),
                ('date', models.CharField(max_length=255, verbose_name='Дата окончания')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс')),
                ('complexity', models.IntegerField(default=0, verbose_name='сложность')),
                ('importance', models.IntegerField(default=0, verbose_name='важность')),
                ('is_in_plans', models.BooleanField(default=True, verbose_name='В планах')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card', verbose_name='карта')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
