# Generated by Django 4.1.7 on 2023-04-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_actiontoideas_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontoideas',
            name='idea',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.idea', verbose_name='Идея'),
        ),
    ]
